# Generated by Django 2.0.1 on 2020-04-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racelist', '0002_auto_20200329_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='racelist',
            name='da',
            field=models.CharField(default=999, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racelist',
            name='itemLink',
            field=models.CharField(default=999, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racelist',
            name='itemLong',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racelist',
            name='itemNumber',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racelist',
            name='itemTime',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racelist',
            name='itemTitle',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racelist',
            name='raceTitle',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racelist',
            name='shiba',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
