# Generated by Django 2.0.1 on 2020-05-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keiba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keiba',
            old_name='full_name',
            new_name='user_name',
        ),
    ]
