# Generated by Django 2.0.1 on 2020-05-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keiba', '0002_auto_20200530_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keiba',
            old_name='user_name',
            new_name='full_name',
        ),
    ]
