# Generated by Django 2.0.1 on 2020-05-30 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
