# Generated by Django 2.0.1 on 2020-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0003_auto_20200531_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='user_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
