# Generated by Django 2.0.1 on 2020-05-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0005_seat_seat_flg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_flg',
            field=models.IntegerField(default=0),
        ),
    ]
