# Generated by Django 2.0.1 on 2020-05-31 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0006_auto_20200601_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='seat_flg',
            new_name='seat_code',
        ),
    ]
