# Generated by Django 2.0.1 on 2020-06-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0007_auto_20200601_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_test',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
